version: '3.9'

services:
  app:
    container_name: next_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: always