version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: next_frontend
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
  storybook:
    build:
      context: .
      dockerfile: storybook.Dockerfile
    container_name: next_storybook
    ports:
      - '6006:6006' 
    volumes:
      - .:/app
      - /app/node_modules